// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMW-7L31o3Uoet1RoQwqHFMDt4OdETuqQ',
    appId: '1:504988713429:web:87490e47e2ce3429cc3d5c',
    messagingSenderId: '504988713429',
    projectId: 'tamm-app-8c990',
    authDomain: 'tamm-app-8c990.firebaseapp.com',
    storageBucket: 'tamm-app-8c990.firebasestorage.app',
    measurementId: 'G-8PKBD7HL3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABDBZiCIqiGv6RHKicAIEoAwNpVy2Cp-w',
    appId: '1:504988713429:android:af07c1ac2f804a21cc3d5c',
    messagingSenderId: '504988713429',
    projectId: 'tamm-app-8c990',
    storageBucket: 'tamm-app-8c990.firebasestorage.app',
  );
}
